### ISSUE TITLE
Infobox for tablecustomization conflicts with gearweel button

### ISSUE THREAD

**Issue by ll-SKY-ll** [etkecc/synapse-admin#110]
Please see in the screenshot, when klicking the button to enable customizations, the gearwheel appears in the same area as the infobox. When trying to klick the gearwheel, it disapperas as soon as the mouse pointer enters the area of the infobox since the infobox itself is not part of the cusstomizable table.....

![Screenshot_20241030_143156](https://github.com/user-attachments/assets/950dd035-b590-4841-bea8-7da4199a0601)

**Comment by aine-etke** [comment]
Not a fix yet, but are you aware that you could drag it?

![image](https://github.com/user-attachments/assets/69ed843f-b6c3-459f-b424-d3c9954e3686)

**Comment by ll-SKY-ll** [comment]
oh lol, it never came to my mind to try that.....

That would work for me, though i dont know how many others are also not aware that they can drag it...

**Comment by aine-etke** [comment]
Unfortunately, [due to how it is implemented in react-admin](https://github.com/marmelab/react-admin/blob/a2d44da750bce450f3b92d370006fcbdbbd33409/packages/ra-ui-materialui/src/preferences/Inspector.tsx#L27-L39), it's not possible to change the starting position properly, so we can't fix that, alas.
