### ISSUE TITLE
 Feature request [Bulk turn on encryption on rooms] 

### ISSUE THREAD

**Issue by nathanael-h** [etkecc/synapse-admin#217]
Hello, thanks for the work on this fork. I'd like to turn on encryption in bulk on multiple rooms. But I'm not sure this would be easy to add here, as I did not saw this in [synapse admin documentation](https://element-hq.github.io/synapse/latest/admin_api/rooms.html), but only in [client-server api](https://spec.matrix.org/v1.12/client-server-api/#protocol-definitions-1).

**Comment by aine-etke** [comment]
Hello,
Unfortunately, Synapse Admin can use only Synapse Admin API features. Client-Server API is not usable in this case, because it requires a user to be present in the room and have corresponding permissions.

I'm closing this one, as there is no suitable Admin API endpoint (and it looks like it won't be added in the future, unless you request one in Synapse repo issues and it will be implemented)
