### ISSUE TITLE
Enhance visibility for darkmode

### ISSUE THREAD

**Issue by ll-SKY-ll** [etkecc/synapse-admin#54]
Currently, the colors on the federation tab are orange with black text for servers with failed federation  in light mode, that is generally easy to read.
But the colors for the darkmode are light orange( #ffb74d ) with white text for the rows with failed federation, the contrast here is really bad and its uncomfortable to read.

![Screenshot_20241003_122420](https://github.com/user-attachments/assets/9a5c77f7-4eaa-4768-98c9-c4712ac7efc1)

a background color like #802727 would enhance the contrast really good

![Screenshot_20241003_121845](https://github.com/user-attachments/assets/0bccd22f-d9d9-48b0-98bf-4082ef82c252)

I tried to find the source for these colors on github, but I have no clue how yarn/js etc works.... 

In the current release package, its in the assets folder, in file index-f-sCgirW.js

**Comment by aine-etke** [comment]
Does this one look good (failed destinations have error icon)?

![image](https://github.com/user-attachments/assets/223250e5-86e0-4eb1-88bb-cadfe162bb7b)
![image](https://github.com/user-attachments/assets/daeff933-5471-4fa3-b5df-e5e9c36e2305)


Coloring whole rows seems like not the best idea, as that causes readability issues, so both background and text colors should be picked carefully. I agree with @beastafk that we'd better stick with theme colors, otherwise the same issue will be raised whenever the theme changes (e.g., due to dependency updates, like it was with reac-admin upgrade)

**Comment by aine-etke** [comment]
@ll-SKY-ll ?

**Comment by ll-SKY-ll** [comment]
> @ll-SKY-ll ?

I think the error icon looks also really good :)

**Comment by aine-etke** [comment]
ok, closing this one as the icones were added in https://github.com/etkecc/synapse-admin/commit/a42efe7edab01bfc6fc86141caf971e0872be6e2 and available in `latest` docker tag and https://admin.etke.cc

**Comment by aine-etke** [comment]
another mention: https://github.com/Awesome-Technologies/synapse-admin/issues/627
