### ISSUE TITLE
Twitchy login screen

### ISSUE THREAD

**Issue by HarHarLinks** [etkecc/synapse-admin#56]
1. enter MXID
2. enter PW
3. no HS selected (dropdown is empty)
4. press Enter

https://github.com/user-attachments/assets/38b81824-aaf6-4c67-802e-079c4c3a3342

Firefox 130.0.1 on LInux

**Comment by aine-etke** [comment]
context: https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3576

Basically, if the allowed HS URLs config value is set to empty array, the login form shows dropdown without any values, instead of (expected) text input.

So, the scope of this one is to treat empty array the same way as `null`/`undefined` for HS URL field
